name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      pages: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          destination_dir: ./
          commit_message: 'Deploy site to GitHub Pages'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
